# URL
jdbc.url=jdbc:mariadb://http://localhost:3309/MyTestDB?serverTimezone=Asia/Seoul
jdbc.username=root
jdbc.password=MyTestDB
jdbc.driverClassName=org.mariadb.jdbc.Driver

# HikariCP‹œ
jdbc.pool.maxPoolSize=10
jdbc.pool.minIdle=5