# 데이터 소스 URL
jdbc.url=jdbc:mariadb://http://localhost:3309/your_project_db?serverTimezone=Asia/Seoul
jdbc.username=root
jdbc.password=my-secret-pw
jdbc.driverClassName=org.mariadb.jdbc.Driver

# HikariCP 설정 예시
jdbc.pool.maxPoolSize=10
jdbc.pool.minIdle=5